### ISSUE TITLE
about Image sampling

### ISSUE THREAD

**Issue by ybu-lxd** [CiaoHe/DiM#1]
Thanks for the Mamba based diffusion model code. Has your team successfully used this code to generate images? Thank you again for your selfless sharing and I look forward to your reply. Wish you the best at work!

**Comment by CiaoHe** [comment]
sure, we have basic results on XL-2

| ckpt(cfg=1.0) | FID-50K | sFID | IS | P | R |
|---------------|---------|------|----|---|---|
|   DiM-XL-2 (1.7M steps)            |    11.16     |   5.99   |  102.5493  |  0.68228 |  0.6382 |

But to be honest, the mamba is quite unstable for large model parameter training. But for smaller size (S / B), the convergence speed is really sharp.

**Comment by ybu-lxd** [comment]
It's good to know that you've achieved basic results on the XL-2. Your conclusions are very valuable to me, especially regarding the values of FID-50K and IS. Thank you again for your selfless sharing

**Comment by CiaoHe** [comment]
> It's good to know that you've achieved basic results on the XL-2. Your conclusions are very valuable to me, especially regarding the values of FID-50K and IS. Thank you again for your selfless sharing

If you want to explore further about Mamba in the diffusion area, you can contact me. Maybe there still is some space to exploration.

**Comment by ybu-lxd** [comment]
Thank you for your reply, I will conduct experiments on my data set immediately.

**Comment by ybu-lxd** [comment]
> > It's good to know that you've achieved basic results on the XL-2. Your conclusions are very valuable to me, especially regarding the values of FID-50K and IS. Thank you again for your selfless sharing
> 
> If you want to explore further about Mamba in the diffusion area, you can contact me. Maybe there still is some space to exploration.

May I ask which data set you did the training on? I did not achieve good results when training the XL structure on my own data set. Also, can you provide the weights? I would be very grateful.

**Comment by CiaoHe** [comment]
sry we cannot provide with ckpt. we trained on IN-1k

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: ybu-lxd ***@***.***>
发送时间: Monday, May 27, 2024 4:40:21 PM
收件人: CiaoHe/DiM ***@***.***>
抄送: He Cao ***@***.***>; Comment ***@***.***>
主题: Re: [CiaoHe/DiM] about Image sampling (Issue #1)


It's good to know that you've achieved basic results on the XL-2. Your conclusions are very valuable to me, especially regarding the values of FID-50K and IS. Thank you again for your selfless sharing

If you want to explore further about Mamba in the diffusion area, you can contact me. Maybe there still is some space to exploration.

May I ask which data set you did the training on? I did not achieve good results when training the XL structure on my own data set. Also, can you provide the weights? I would be very grateful.

―
